services:
  carla_proxy:
    build: .
    tty: true
    secrets:
      - carla_ssh_key
    expose:
      - 3000
      - 3001
      - 3002
    healthcheck:
      test: ['CMD', 'printf', '"GET / HTTP/1.1\n\n" > /dev/tcp/127.0.0.1/3000']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    command: ssh -i /run/secrets/carla_ssh_key -o StrictHostKeyChecking=no -4 -L *:3000:ipvsgpu1.informatik.uni-stuttgart.de:3000 -L *:3001:ipvsgpu1.informatik.uni-stuttgart.de:3001 -L *:3002:ipvsgpu1.informatik.uni-stuttgart.de:3002 bartelmk@ipvslogin.informatik.uni-stuttgart.de

  carla_ingest:
    build: ../../
    depends_on:
      carla_proxy:
        condition: service_healthy
    environment:
      - CARLA_URL=carla_proxy
      - CARLA_PORT=3000
      - PYTHONPATH=/code/src
    volumes:
      - "../../:/code"
    command: python3 /code/src/location_cloaking/utils/map/ingest.py

  carla_generate_traffic:
    build: ../../
    depends_on:
      carla_ingest:
        condition: service_completed_successfully
    environment:
      - CARLA_URL=carla_proxy
      - CARLA_PORT=3000
      - PYTHONPATH=/code/src
    volumes:
      - "../../:/code"
    command: python3 /code/src/location_cloaking/utils/map/generate_random_traffic.py

  client:
    build: .
    depends_on:
      - carla_generate_traffic
      - echo_agent
    volumes:
      - "./modules/client/:/code"
    ports:
      - 5000:5000
    environment:
      - CARLA_URL=carla_proxy
      - CARLA_PORT=3000
      - ECHO_AGENT_URL=http://echo_agent:5000

  echo_agent:
    build: .
    depends_on:
      - echo_db
      - location_based_service
    # somehow need to wait until db is ACTUALLY ready and not just healthy.
    volumes:
      - "./modules/echo_agent/:/code"
    environment:
      - LOCATION_SERVER_URL=http://location_based_service:5000
      - ECHO_DB_HOST=echo_db
      - ECHO_DB_USER=echo_agent
      - ECHO_DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    
  location_based_service:
    build: .
    depends_on:
      - carla_generate_traffic
    ports:
      - 5001:5000 # browser must be able to access it
    volumes:
      - "./modules/location_based_service/:/code"

  carla_visualization_backend:
    build: ../../
    depends_on:
      - carla_generate_traffic
    environment:
      - CARLA_URL=carla_proxy
      - CARLA_PORT=3000
      - PYTHONPATH=/code/src
    expose:
      - 8200
    ports:
      - 8200:8200
    volumes:
      - "../../:/code"
    command: python3 /code/src/carla_visualization/server.py

  carla_visualization_frontend:
    build: ../../../carla-frontend/
    depends_on:
      - carla_visualization_backend
    ports:
      - 8080:3000

  echo_db:
    image: mongo
    restart: always
    secrets:
       - db_root_password
       - db_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    # Exposes default port 27017
    volumes:
      - echo_db_volume:/data/db

secrets:
   db_password:
     file: secrets/db_password.txt
   db_root_password:
     file: secrets/db_root_password.txt
   carla_ssh_key:
     file: secrets/ipvs_login


volumes:
  echo_db_volume: