# Network topology: all services are in the docker network,
# except the service "client" (so that it can connect to carla).
services:
  location_based_service:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - "./modules/location_based_service/:/code"

  echo_agent:
    build: .
    depends_on:
      - echo_db
    # somehow need to wait until db is ACTUALLY ready and not just healthy.
    volumes:
      - "./modules/echo_agent/:/code"
    ports:
      - "5001:5000" # Bind to 5001 because 5000 is already in use by service "client"
    environment:
      - LOCATION_SERVER_URL=http://location_based_service:5000
      - ECHO_DB_HOST=echo_db
      - ECHO_DB_USER=echo_agent
      - ECHO_DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

  client:
    build: .
    volumes:
      - "./modules/client/:/code"
    network_mode: "host" # The client has to be part of the local network in order to access a remote carla instance
    environment:
      - CARLA_URL=localhost
      - CARLA_PORT=3000
      - ECHO_AGENT_URL=http://localhost:5001      

  echo_db:
    image: mysql:5.7
    restart: always
    secrets:
       - db_root_password
       - db_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: echo_agent
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    expose:
      - '3306'
    volumes:
      - echo_db_volume:/var/lib/mysql

secrets:
   db_password:
     file: secrets/db_password.txt
   db_root_password:
     file: secrets/db_root_password.txt

volumes:
  echo_db_volume: