# This module contains all services needed to run
# the echo_agent in development mode (i.e. the python flask
# servers are running in debug mode with hot reloading).
# 
# WARNING: this is a prototype, no production configuration is included.
version: '3.8'
services:
  client:
    build:
      context: ../../src/echo_agent
      dockerfile: ../../deployment/echo_agent/dockerfile
    depends_on:
      - carla_generate_traffic
      - echo_agent
    volumes:
      - "../../src/echo_agent/modules/client/:/code"
    ports:
      - ${ECHO_AGENT_CLIENT_PORT:-5000}:5000
    environment:
      - CARLA_URL=${CARLA_HOST:?error}
      - CARLA_PORT=${CARLA_PORT_BASE:?error}
      - ECHO_AGENT_URL=http://echo_agent:5000

  echo_agent:
    build:
      context: ../../src/echo_agent
      dockerfile: ../../deployment/echo_agent/dockerfile
    depends_on:
      - location_based_service
    volumes:
      - "../../src/echo_agent/modules/echo_agent/:/code"
      - "echo_agent_storage:/storage:rw"
    environment:
      - LOCATION_SERVER_URL=http://location_based_service:5000
      - NUMBER_OF_DUMMIES=3
      - STORAGE_PATH=/storage
    ports:
      - ${ECHO_AGENT_ECHO_AGENT_PORT:-5001}:5000 # browser must be able to access it
    
  location_based_service:
    build:
      context: ../../src/echo_agent
      dockerfile: ../../deployment/echo_agent/dockerfile
    depends_on:
      - carla_generate_traffic
    ports:
      - ${ECHO_AGENT_LOCATION_BASED_SERVICE_PORT:-5002}:5000 # browser must be able to access it
    volumes:
      - "../../src/echo_agent/modules/location_based_service/:/code"

volumes:
  echo_agent_storage: